name: ci
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "8"
    - uses: actions/checkout@v2.3.4
    - uses: coursier/cache-action@v6
    - uses: reviewdog/action-setup@ae87162d7ffe105a36707dd9390d11654ea8f7ba
    - run: reviewdog -version
    - run: sbt -no-colors Test/compile | tee log.txt
    - env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # scalacやsbtだとwarn出ない
        # https://github.com/reviewdog/errorformat/blob/master/fmts/scala.go
        echo log.txt | reviewdog -reporter=github-pr-review -f=sbt-scalastyle
        echo log.txt | reviewdog -reporter=github-check -f=sbt-scalastyle
